### ISSUE TITLE
Endless Loop With Lower

### ISSUE THREAD

**Issue by jon-mcmillan** [nelsam/gorq#6]
``` go
type X struct {
    Name string
}

ref := new(X)
datastore.Query(ref).Where().Equal(Lower(&ref.Name), "foo").Select()
```

Code structured like this creates an endless loop in `QueryPlan.argOrColumn` at `/gorq/plans/query_plans.go:288`.

**Comment by nelsam** [comment]
I believe I just solved this.  Let me know if it's still an issue after a09472878ba73238070fda28d6d64ace839ab30d.
